// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('bankLogin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('bankLogin', async function() {
    await driver.get("http://demo.guru99.com/V1/index.php")
    await driver.manage().window().setRect(1382, 744)
    await driver.findElement(By.name("btnLogin")).click()
    await driver.findElement(By.name("btnReset")).click()
    {
      const element = await driver.findElement(By.name("btnLogin"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,156)")
    await driver.findElement(By.linkText("here")).click()
    await driver.findElement(By.name("emailid")).click()
    await driver.findElement(By.name("emailid")).sendKeys("shei@gmail.com")
    {
      const element = await driver.findElement(By.name("btnLogin"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.name("btnLogin")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,74)")
    await driver.findElement(By.css("tr:nth-child(4) > .accpage")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css("center:nth-child(1)")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2)")).click()
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2)")).click()
    await driver.findElement(By.name("frmLogin")).click()
    await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(2)")).click()
    await driver.findElement(By.name("uid")).click()
    await driver.findElement(By.name("uid")).sendKeys("mngr297856")
    await driver.findElement(By.name("password")).click()
    {
      const element = await driver.findElement(By.name("btnLogin"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.name("btnLogin")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("uid")).click()
    await driver.findElement(By.name("uid")).sendKeys("mngr297856")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("rYmetuq")
    await driver.findElement(By.name("btnLogin")).click()
  })
})
