const {userName, password, submit, loginMessageTitle, loginMessageDescription, currentUrl} = require('./page_objects/login');
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome')
const chromedriver = require('chromedriver')

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build());

describe('failed_login', function() {
  this.timeout(30000)
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_case_13', async function() {
    await currentUrl
    await driver.manage().window().setRect(806, 668)
    await driver.findElement(By.linkText("New Tours")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(2)"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    await driver.findElement(By.css("a:nth-child(2)")).click()
  })
})

