// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://demo.guru99.com/test/newtours/")
    await driver.manage().window().setRect(1116, 1020)
    await driver.findElement(By.name("userName")).click()
    await driver.findElement(By.name("userName")).sendKeys("MPAZ")
    await driver.findElement(By.name("password")).sendKeys("123")
    await driver.findElement(By.name("submit")).click()
  })
})
