// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_login', async function() {
    await driver.get("http://demo.guru99.com/insurance/v1/index.php")
    await driver.manage().window().setRect(2576, 1056)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("usuario")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123456")
    await driver.findElement(By.name("submit")).click()
  })
})
