// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login_insurance', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login_insurance', async function() {
    await driver.get("http://demo.guru99.com/insurance/v1/index.php")
    await driver.manage().window().setRect(1288, 698)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("usuario")
    {
      const element = await driver.findElement(By.name("submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("password")).sendKeys("password")
    await driver.findElement(By.name("submit")).click()
  })
})
