// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const chrome = require('selenium-webdriver/chrome')
const chromedriver = require('chromedriver')

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build())

describe('payment section', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('payment section', async function() {
    await driver.get("http://demo.guru99.com/payment-gateway/process_purchasetoy.php")
    await driver.manage().window().setRect(1178, 721)
    await driver.findElement(By.id("card_nmuber")).click()
    await driver.findElement(By.id("card_nmuber")).sendKeys("1234567890987654")
    await driver.findElement(By.id("month")).click()
    {
      const dropdown = await driver.findElement(By.id("month"))
      await dropdown.findElement(By.xpath("//option[. = '01']")).click()
    }
    await driver.executeScript("window.scrollTo(0,456)")
    await driver.findElement(By.id("year")).click()
    {
      const dropdown = await driver.findElement(By.id("year"))
      await dropdown.findElement(By.xpath("//option[. = '2027']")).click()
    }
    await driver.findElement(By.id("cvv_code")).click()
    await driver.findElement(By.id("cvv_code")).sendKeys("111")
    await driver.findElement(By.name("submit")).click()
    {
      const element = await driver.findElement(By.css(".button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
