// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const chrome = require('selenium-webdriver/chrome')
const chromedriver = require('chromedriver')

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build())

describe('register_succesfully', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('register_succesfully', async function() {
    await driver.get("http://demo.guru99.com/test/newtours/")
    await driver.manage().window().setRect(770, 824)
    await driver.findElement(By.css("tr:nth-child(10) a")).click()
    await driver.findElement(By.name("firstName")).click()
    await driver.findElement(By.name("firstName")).sendKeys("Luana")
    await driver.findElement(By.name("lastName")).sendKeys("Ozara")
    await driver.findElement(By.css("form tr:nth-child(3) > td:nth-child(2)")).click()
    await driver.findElement(By.name("phone")).click()
    await driver.findElement(By.name("phone")).sendKeys("5556575859")
    await driver.findElement(By.id("userName")).click()
    await driver.findElement(By.id("userName")).sendKeys("luannna@gmail.com")
    await driver.findElement(By.name("address1")).click()
    await driver.findElement(By.name("address1")).sendKeys("Mex")
    await driver.findElement(By.name("city")).sendKeys("Mex")
    await driver.findElement(By.name("state")).sendKeys("Mex")
    await driver.findElement(By.name("postalCode")).click()
    await driver.findElement(By.name("postalCode")).sendKeys("11840")
    await driver.findElement(By.name("country")).click()
    {
      const dropdown = await driver.findElement(By.name("country"))
      await dropdown.findElement(By.xpath("//option[. = 'MEXICO']")).click()
    }
    await driver.findElement(By.name("country")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("luannna")
    await driver.findElement(By.name("password")).sendKeys("1234567")
    await driver.findElement(By.name("confirmPassword")).sendKeys("1234567")
    await driver.findElement(By.name("submit")).click()
  })
})

